# -*- coding: utf-8 -*-
"""Number_guessing_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALVp9VHVx7yeh5RbSKGBoFuXrUMPRbNq
"""

import random
top_of_range = input("Type a number")

if top_of_range.isdigit():
   top_of_range = int(top_of_range)

   if top_of_range <=0:
     print('Please type a number larger than zero next time')
     quit()

else:
    print('Please type a number next time')
    quit()

random_number = random.randint(0,top_of_range)
guesses = 0

while True:
  guesses+=1
  user_guess = input("Make a guess: ")
  if user_guess.isdigit():
      user_guess = int(user_guess)

  else:
      print("Plese type valid number next time.")
      continue

  if user_guess == random_number:
      print("You got it!")
      break

  elif user_guess > random_number:
      print("You were above the number! ")

  else:
      print("You were below the number!")
print("You got it in ",guesses,"guesses")